[build]
  command = "npm run docs"

# Add branch deployment settings
[context."release/*"]
  command = "npm run docs"

[context."staging/*"]
  command = "npm run docs"

# For versions like v1.2.3, v2.0.1, etc.
[[redirects]]
  from = '/v0.3.0/*'
  to = 'https://release-v0-2-3--z-changeset-practice.netlify.app/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/v0.2.3/*'
  to = 'https://release-v0-2-3--z-changeset-practice.netlify.app/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/v0.2.2/*'
  to = 'https://release-v0-2-2--z-changeset-practice.netlify.app/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/v0.2.1/*'
  to = 'https://release-v0-2-1--z-changeset-practice.netlify.app/:splat'
  status = 200
  force = true  