name: Tag Processing

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'

jobs:
  create-release-branch:
    # Prevents tag processing on forks
    if: github.repository == 'zeroedin/z-changeset-practice'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for proper branching
      
      - name: Create release branch
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_BRANCH="release/${TAG_NAME}"
          
          # Create and push release branch
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"
          
          echo "Created release branch: $RELEASE_BRANCH"
